apiVersion: v1
kind: Service
metadata:
  name: btc-serving
  namespace: {{ .Values.namespace }}
  labels: { app: btc-serving }
spec:
  type: {{ .Values.service.type }}
  selector: { app: btc-serving }
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
