apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ksaName }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.gcpServiceAccount .Values.gcpProject | quote }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: btc-mlops
