apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: btc-serving
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/gottfriedgenin/btc-mlops
    targetRevision: main
    path: k8s/base/serving
  destination:
    server: https://kubernetes.default.svc
    namespace: serving
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
