apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.x.x
      helm:
        releaseName: kube-prom
        valueFiles:
          - $values/platform/helm/values/prometheus-stack.yaml
    - repoURL: https://github.com/gottfriedgenin/btc-mlops
      targetRevision: main
      ref: values
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # CRDs are huge; SSA avoids "too long" errors
